version: '3.7'
services:

  web:
    container_name: pygin
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./app:/app
    # command: python app.main:app --reload --host 0.0.0.0 --port 5000
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: gin_db

  pgAdmin:
    container_name: pgAdmin
    restart: unless-stopped
    image: dpage/pgadmin4:6.18
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
        - ./data/pgadmin:/var/lib/pgadmin
    ports:
        - "5050:5050"
    depends_on:
        - db